### ISSUE TITLE
"Drunk" is broken

### ISSUE THREAD

**Issue by CrackerHax** [EmpireMUD/EmpireMUD-2.0-Beta#130]
Not only is being drunk really annoying because it turns the map but it pretty much makes the tavern worthless. Also drunk does not show up on "affects" list. It should probably be removed from the game so beverages can be worth making.

**Comment by Hitsume** [comment]
Getting drunk is the main purpose of the tavern beverages. If you want a way to get liquids which don't make you drunk, the fountain, river and well all do that. (Also, milk.) How would removing drunkenness make beverages worth making? And how does having it make the tavern worthless?

Being drunk **does** show up on the affects list: "[You are inebriated.](http://i.imgur.com/YcMDsXJ.png)" ([code link](https://github.com/EmpireMUD/EmpireMUD-2.0-Beta/blob/beta-dev/src/act.informative.c#L1788)) It doesn't show up in the MSDP affects data (because technically, it isn't one). But that's a separate thing. Lots of useful information is missing from that, like hunger and thirst.

"Drunk" is not useful in combat. Or at all, really - it's a 'just for fun' feature. But it's not broken.

**Comment by CrackerHax** [comment]
Losing Navigation ability is fun? It is just too much trouble.... If players are going to waste time and city slots (and hunting down 20 hops and 20 barley) making a tavern then it should produce something positive (and it requires a constant stream of harvested goods). It's really not a fun feature. How about some sort of alcohol buff? Or how about alcohol satisfying both hunger and thirst at the same time (without losing the navigation feature). 

Also I guess I should have mentioned... I only drank it once and I was made drunk. And it lasted a long time.

**Comment by EmpireMUD** [comment]
I'm happy with the "drunk" system as-is. If you don't want to stumble
around drunk, try not drinking.

The amount you drink at a time is based on how thirsty you are, so it may
be enough to get you drunk quickly.

I don't think alcohol making you less hungry/thirsty is in any way
realistic, as actual alcohol makes you MORE thirsty.

**Comment by CrackerHax** [comment]
Beer was used to feed egyptians working on the pyramids. It is also known as liquid bread. But ok, I will just stop posting here since you seem pretty defensive and hate everything I have posted. Take care.

**Comment by EmpireMUD** [comment]
Thank you.

**Comment by CrackerHax** [comment]
Why put your code on github at all if you don't work well with others? As if anybody in their right mind would waste their time pushing any changes for this.
